### ISSUE TITLE
Scylla throwing an error

### ISSUE THREAD

**Issue by hexadiam** [lanmaster53/recon-ng#116] opened 2020-08-16 23:52 UTC
Running a query throws an error. It definitely is finding data but barfs before processing it. To wit:

[recon-ng][xxx.com][scylla] > info

      Name: Scylla Bulk Credential Harvester
    Author: Tim Tomes (@lanmaster53)
   Version: 1.2

Description:
  Harvests credentials from the scylla.sh API using domains as input. Updates the 'credentials' and
  'contacts' tables with the results.

Options:
  Name    Current Value  Required  Description
  ------  -------------  --------  -----------
  SIZE    100            yes       number of results per page
  SOURCE  default        yes       source of input (see 'info' for details)

Source Options:
  default        SELECT DISTINCT domain FROM domains WHERE domain IS NOT NULL
  <string>       string representing a single input
  <path>         path to a file containing a list of inputs
  query <sql>    database query returning one column of inputs

[recon-ng][xxx.com][scylla] > run
[*] No validator required.
[*] DATABASE => /home/hunter/.recon-ng/workspaces/xxx.com/data.db
[*] QUERY => SELECT DISTINCT domain FROM domains WHERE domain IS NOT NULL
[*] DATABASE => /home/hunter/.recon-ng/workspaces/xxx.com/data.db
[*] QUERY => INSERT OR REPLACE INTO dashboard (module, runs) VALUES ('recon/domains-credentials/scylla', COALESCE((SELECT runs FROM dashboard WHERE module='recon/domains-credentials/scylla')+1, 1))
[*] ========================= REQUEST =========================
url:    https://scylla.sh/search?q=Email%3A%22%40xxx.com%22&size=50&from=0
method: GET /search?q=Email%3A%22%40xxx.com%22&size=50&from=0
header: User-Agent: Chrome/42.0.2311.135 Safari/537.36 Edge/12.246
header: Accept-Encoding: gzip, deflate
header: Accept: application/json
header: Connection: keep-alive
header: Authorization: Basic c2FtbXk6QmFzaWNQYXNzd29yZCE=
[*] ========================= RESPONSE =========================
status: 200 OK
header: Date: Sun, 16 Aug 2020 23:44:46 GMT
header: Server: Apache
header: Content-Length: 8918
header: Keep-Alive: timeout=5, max=100
header: Connection: Keep-Alive
header: Content-Type: application/json
body:   b'[{"fields":{"domain":"dropbox.com","email":"abc.def@xxx.com","passhash":"dfe@E$WSDfsddddssd3##"},"id":"b47379e0e0db37a0dc482fc02273fd85"}, etc etc etc, {"domain":"dropbox.com","email":"ghi.jhk@xxx.com","passhash":"$2a$08$44533mnddgr9x/R4wh.LWYlMjG7K0Z33EoCgiHvi5Cfe2pJu"},"id":"156fe23d566e91c8a4c8a1ae32sdf885"}]\n'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hunter/recon-ng/recon/core/module.py", line 347, in do_run
    self.run()
  File "/home/hunter/recon-ng/recon/core/module.py", line 341, in run
    self.module_run(*params)
  File "/home/hunter/.recon-ng/modules/recon/domains-credentials/scylla.py", line 35, in module_run
    leak = cred['_source'].get('Domain')
KeyError: '_source'
------------------------------------------------------------
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

**Comment by kpomeroy1979** [comment] 2020-09-14 21:49
I get the exact same error / issue. I posted in the Slack Channel to see if anyone has a solution.

**Comment by lanmaster53** [comment] 2020-09-25 01:45
This should be fixed now. FTR, this is the repository for the framework, not individual modules. There were several issues on the marketplace repo that this was a duplicate of. They have been resolved.

**Closed by lanmaster53** 2020-09-25 01:45 UTC

**Comment by kpomeroy1979** [comment] 2020-09-25 06:37
Thank you sir for the hard work. Much appreciated.

**Comment by lanmaster53** [comment] 2020-09-25 14:45
My pleasure!
