### ISSUE TITLE
Dependency Installation censys

### ISSUE THREAD

**Issue by gmatsy** [lanmaster53/recon-ng#149] opened 2021-12-17 23:09 UTC
try to install the censys modules and it points me to [!] Module 'recon / netblocks-hosts / censys_netblock' disabled. Dependency required: '' censys.ipv4 ''. this occurs with versions of censys from 2.0.0 onwards. I installed version 1.1.1 since I thought it was because of it and it no longer shows me that error, but in the censys modules you can see the message of "outdated". How can i fix this?
![Screenshot from 2021-12-17 18-03-37](https://user-images.githubusercontent.com/46139556/146617915-4dba4b2b-adfb-448b-9b63-7a1682573615.png)
![Screenshot from 2021-12-17 18-04-15](https://user-images.githubusercontent.com/46139556/146617931-2522ab41-3d1f-4aa1-a11c-47bde6e8081f.png)

**Comment by saltasatelites** [comment] 2022-01-24 20:45
I see this topic is relatively old but I've the same problem. I'm using Archlinux with all the dependencies installed, inclusive the python-censys, version 2.1.1-1 from the AUR repositorie (compiled from https://github.com/censys/censys-python) and shows the same errors.
I've no clear if the problem is related with Recon-ng or with the python-censys package itself.

` Module 'recon/netblocks-hosts/censys_netblock' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.`

` Module 'recon/netblocks-companies/censys_netblock_company' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.`

` Module 'recon/hosts-hosts/censys_hostname' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.`

` Module 'recon/hosts-hosts/censys_query' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.`

` Module 'recon/domains-hosts/censys_domain' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.`

`Module 'recon/companies-hosts/censys_org' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'.`

` Module 'recon/companies-contacts/censys_email_address' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'. `

` Module 'recon/domains-companies/censys_companies' disabled. Dependency required: 'me 'CensysIPv4' from 'censys.search' (/usr/lib/python3.10/site-packages/censys/search/__init__.py)'. `


Regards

**Comment by saltasatelites** [comment] 2022-01-27 16:49
Censys have open a new issue at censys-recon-ng about this this topic.
https://github.com/censys/censys-recon-ng/issues/5

**Comment by lanmaster53** [comment] 2024-05-02 20:14
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).

A fix has been merged that may address this issue.

**Closed by lanmaster53** 2024-05-02 20:14 UTC
