### ISSUE TITLE
AttributeError: module 'string' has no attribute 'lowercase' on "Python 3.7.5"

### ISSUE THREAD

**Issue by epinna** [lanmaster53/recon-ng#63] opened 2020-01-02 14:37 UTC
Hello, the cli fails with `Python 3.7.5`. 

```
File "/tmp/recon-ng/recon-cli", line 89, in <module>
    recon_cli(args)
  File "/tmp/recon-ng/recon-cli", line 25, in recon_cli
    x.start(*options)
  File "/tmp/recon-ng/recon/core/base.py", line 76, in start
    self._init_workspace(workspace)
  File "/tmp/recon-ng/recon/core/base.py", line 202, in _init_workspace
    self._migrate_db()
  File "/tmp/recon-ng/recon/core/base.py", line 258, in _migrate_db
    tmp = self.get_random_str(20)
  File "/tmp/recon-ng/recon/core/framework.py", line 229, in get_random_str
    return ''.join(random.choice(string.lowercase) for i in range(length))
  File "/tmp/recon-ng/recon/core/framework.py", line 229, in <genexpr>
    return ''.join(random.choice(string.lowercase) for i in range(length))
AttributeError: module 'string' has no attribute 'lowercase'
```

I think you should use `ascii_lowercase` instead.

**Comment by lanmaster53** [comment] 2020-01-02 15:41
Duplicate of #39.

**Comment by lanmaster53** [comment] 2020-01-02 15:42
Duplicate of #39

**Comment by lanmaster53** [comment] 2020-01-02 15:43
This is already resolved in the staging branch.

**Closed** 2020-01-13 17:43 UTC
Labels: duplicate
