### ISSUE TITLE
won't run, invalid synthax

### ISSUE THREAD

**Issue by e2002e** [lanmaster53/recon-ng#55] opened 2019-12-13 10:42 UTC
Hi, I cannot run it because there are "f" in various places before strings, for instance:
  File "recon-ng", line 16
    print(f"{Colors.R}[!] Module 'readline' not available. Tab complete disabled.{Colors.N}")
i was retyping it since there are only two of it in recon-ng but when I saw it goes down into the lib folder I stopped, i'm not sure if this is a technique or a typo, but it won't run with python3 or 3.5.

**Comment by lanmaster53** [comment] 2019-12-13 14:42
Duplicate #41.

**Comment by lanmaster53** [comment] 2019-12-13 14:43
Duplicate of #41.

**Comment by lanmaster53** [comment] 2019-12-13 14:46
https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#prerequisites

**Closed by lanmaster53** 2019-12-13 14:46 UTC
