### ISSUE TITLE
findsubdomains module 'lxml' has no attribute 'html'

### ISSUE THREAD

**Issue by l4jos** [lanmaster53/recon-ng#16] opened 2019-09-22 12:41 UTC
Installed recon-ng 5.0.1 from apt repository and tried out findsubdomains module.

options set SOURCE website.site
[!] Module 'lxml' has no attribute 'html'

**Comment by lanmaster53** [comment] 2019-09-23 18:13
lxml is listed in the REQUIREMENTS file, so whoever set up the apt repository for whatever distribution you are using (I don't have any control or oversight of that) is not meeting the REQUIREMENTS for the framework. This sounds like an issue for their bug tracker.

**Comment by l4jos** [comment] 2019-09-30 09:02
I'm having the issue here as well... All requirements are already satisfied.

Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from -r REQUIREMENTS (line 4)) (4.3.4

**Comment by lanmaster53** [comment] 2019-10-08 12:51
I still can't replicate the error. It's working fine here. I believe there is something confusing your python environments on whatever system you are using.

**Comment by lanmaster53** [comment] 2019-10-08 12:52
However, the module doesn't return anything anyway, even for domains that the website clearly shows results for. The module itself appears to need updating as well, but that's a separate issue from what you're experiencing.

**Comment by naltun** [comment] 2019-10-09 18:27
@lanmaster53 I am getting the same error.

I am running Arch Linux with the BlackArch repos (from which I installed `recon-ng` via `pacman -S blackarch/recon-ng`). The dependencies are:
![image](https://user-images.githubusercontent.com/7507990/66509225-952e0980-eaa0-11e9-941d-731412a32c62.png)

I `grep` for current installed packages:
![image](https://user-images.githubusercontent.com/7507990/66509270-af67e780-eaa0-11e9-9fb0-6495f461d849.png)

Python version is:
![image](https://user-images.githubusercontent.com/7507990/66509285-b8f14f80-eaa0-11e9-9e6c-cf88324dcfdb.png)

I may install by hand later and compare. I'll update.

**Comment by naltun** [comment] 2019-10-09 19:13
@lanmaster53 I just installed the repo by hand and got the same error when running with the `recon/domains-host/findsubdomains` module:
![image](https://user-images.githubusercontent.com/7507990/66512458-fe188000-eaa6-11e9-9e1b-3a4d11360b74.png)

Environment:
`python 3.7.4`
`pip 19.0.3`

Steps to reproduce:
1. Clone the repo
2. Create the virtual environment:
    * `$ python3 -m venv env`
3. Enter the environment:
    * `$ source env/bin/activate`
4. Install the requirements:
    * `$ pip3 install -r REQUIREMENTS`
5. Run `recon-ng`, and install the `findsubdomains` module
6. Set SOURCE to a valid domain
7. `run`

**Comment by lanmaster53** [comment] 2019-10-09 20:26
That is so weird. I need to test with a fresh build later and see if i can replicate. Thanks!

**Comment by lanmaster53** [comment] 2019-10-16 02:41
I just did a clean install and everything worked fine. No issues. I've seen your issue before and I am certain it's an environment confusion issue on your end. Figuring out what is causing the confusion is the trick.

If it makes you feel any better, the module doesn't return anything right now anyway. The site has changed and the parser needs to be updated. You can track this at https://github.com/lanmaster53/recon-ng-marketplace/issues/73. Closing this for now since it appears to be a localized environmental issue.

**Closed by lanmaster53** 2019-10-16 02:41 UTC
