### ISSUE TITLE
AttributeError: 'HTMLParser' object has no attribute 'unescape' 

### ISSUE THREAD

**Issue by valkyrie-ops** [lanmaster53/recon-ng#138] opened 2021-03-14 23:24 UTC
Hello. When installing the XSSed module and running it with some domains, there is no problem. However, when running it with cisco.com it has thrown me an error, which has made me doubt if the other domains are 100% accurate in the results. I attach the screenshot of the error.

![image](https://user-images.githubusercontent.com/80233401/111087924-7ed87880-84f2-11eb-96de-b736d49677ce.png)

(I have also tried the solution mentioned here: https://gitmemory.com/issue/lanmaster53/recon-ng/133/782824509, however it has not worked either)

**Comment by Jedarc** [comment] 2021-03-17 01:56
I believe it is the same problem presented here:
https://github.com/lanmaster53/recon-ng/issues/133

**Comment by jonathandkyle** [comment] 2021-04-09 12:38
I have the same issue with fullcontact module.

**Comment by lanmaster53** [comment] 2021-08-25 03:10
Duplicate of #133

**Comment by lanmaster53** [comment] 2021-08-25 03:11
This will be fixed once I push the fix to the master branch.

**Closed** 2021-08-25 03:18 UTC
